/home/long/miniconda3/envs/docavatar/lib/python3.12/site-packages/gradio/blocks.py:1974: UserWarning: A function returned too many output values (needed: 0, returned: 1). Ignoring extra values.
    Output components:
        []
    Output values returned:
        [""]
  warnings.warn(
Traceback (most recent call last):
  File "/home/long/miniconda3/envs/docavatar/lib/python3.12/site-packages/gradio/queueing.py", line 716, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/long/miniconda3/envs/docavatar/lib/python3.12/site-packages/gradio/route_utils.py", line 349, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/long/miniconda3/envs/docavatar/lib/python3.12/site-packages/gradio/blocks.py", line 2274, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/long/miniconda3/envs/docavatar/lib/python3.12/site-packages/gradio/blocks.py", line 1793, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/long/miniconda3/envs/docavatar/lib/python3.12/site-packages/gradio/utils.py", line 754, in async_iteration
    return await anext(iterator)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/long/miniconda3/envs/docavatar/lib/python3.12/site-packages/gradio/utils.py", line 745, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/long/miniconda3/envs/docavatar/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/long/miniconda3/envs/docavatar/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2476, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/long/miniconda3/envs/docavatar/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 967, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/long/miniconda3/envs/docavatar/lib/python3.12/site-packages/gradio/utils.py", line 728, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "/home/long/miniconda3/envs/docavatar/lib/python3.12/site-packages/gradio/utils.py", line 892, in gen_wrapper
    response = next(iterator)
               ^^^^^^^^^^^^^^
  File "/home/long/mnt/d/AIPJ/016DocAvatar/docavatardev/docavatar_gradio.py", line 1508, in convert_to_markdown
    if key and created_leader:
               ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'created_leader' where it is not associated with a value
